# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and deploy swift-connector-ui

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install and build
      run: |
        npm ci
        npm run build --if-present
    - name: deploy
      env:
        my_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "beatofangel@gmx.com"
        git config --global user.name "beatofangel"
        cd dist
        git init
        git add -A .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://$my_token@github.com/beatofangel/swift-connector-ui-release.git" master:master
